name: Validate Renovate config

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Validate Renovate config
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js v24.x
      uses: actions/setup-node@v7
      with:
        node-version: '24.x'
        cache: 'npm'
    - name: Install Packages
      run:  npm ci
    - name: Validate Renovate config
      run: npm test

  scan-secrets:
    uses: digicatapult/shared-workflows/.github/workflows/scan-secrets.yml@main
    permissions:
      contents: read
